blank_issues_enabled: false
contact_links:
  - name: Course Resources
    url: https://github.com/KU-GEOI-525-2023
    about: Access course materials and project repositories
  - name: GitHub Discussions
    url: https://github.com/orgs/KU-GEOI-525-2023/discussions
    about: Join community discussions about the course
